# Generated by Django 4.2.3 on 2023-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='google_map',
            field=models.TextField(null=True),
        ),
    ]
