# Generated by Django 4.2.3 on 2023-09-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_alter_summary_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='number_of_firefighters',
            field=models.CharField(default=21, max_length=255),
            preserve_default=False,
        ),
    ]
