# Generated by Django 4.2.3 on 2023-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_summary_number_of_firefighters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='google_map',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='summary',
            name='safe_to_leave',
            field=models.CharField(max_length=255),
        ),
    ]
