# Generated by Django 4.2.3 on 2023-09-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_alter_summary_google_map_alter_summary_safe_to_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='direction_and_speed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='firefighters_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='google_map',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='location_of_fire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='number_of_firefighters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='safe_to_leave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='what_is_on_fire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
