# Generated by Django 4.2.3 on 2023-07-10 03:30

from django.db import migrations, models
import user_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[user_auth.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[user_auth.validators.validate_name]),
        ),
    ]
