# Generated by Django 4.2.3 on 2023-07-10 06:05

from django.db import migrations, models
import user_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[user_auth.validators.validate_email]),
        ),
    ]
