# Generated by Django 4.2.3 on 2023-07-10 06:36

from django.db import migrations, models
import user_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user_auth.validators.validate_email], verbose_name='email address'),
        ),
    ]
