# Generated by Django 4.2.3 on 2023-07-20 07:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surburbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc_fid', models.IntegerField(unique=True)),
                ('sal_code21', models.CharField(max_length=255)),
                ('sal_name21', models.CharField(max_length=255)),
                ('ste_code21', models.CharField(max_length=255)),
                ('ste_name21', models.CharField(max_length=255)),
                ('aus_code21', models.CharField(max_length=255)),
                ('aus_name21', models.CharField(max_length=255)),
                ('areasqkm21', models.FloatField()),
                ('loci_uri21', models.CharField(max_length=255)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(srid=7844)),
            ],
        ),
    ]
