# Generated by Django 4.2.3 on 2023-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0002_remove_surburbs_id_alter_surburbs_ogc_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surburbs',
            name='ogc_fid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
