# Generated by Django 4.2.3 on 2023-07-20 08:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0003_alter_surburbs_ogc_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surburbs',
            name='areasqkm21',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='aus_code21',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='aus_name21',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='loci_uri21',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='sal_code21',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='sal_name21',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='shape_leng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='ste_code21',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='ste_name21',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surburbs',
            name='wkb_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=7844),
        ),
    ]
