# Generated by Django 4.2.3 on 2023-07-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0004_alter_surburbs_areasqkm21_alter_surburbs_aus_code21_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surburbs',
            new_name='Suburbs',
        ),
    ]
