# Generated by Django 4.2.3 on 2023-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0008_alter_suburbs_wkb_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuburbData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suburb', models.CharField(max_length=255)),
                ('SAL_CODE', models.CharField(max_length=10)),
                ('Median_age_of_persons', models.FloatField()),
                ('Median_mortgage_repayment', models.FloatField()),
                ('Median_total_personal_income', models.FloatField()),
                ('Median_rent_weekly', models.FloatField()),
                ('Median_total_family_income', models.FloatField()),
                ('Average_number_of_persons_per_bedroom', models.FloatField()),
                ('Median_total_household_income_weekly', models.FloatField()),
                ('Average_household_size', models.FloatField()),
                ('Counted_at_home_on_Census_Night', models.IntegerField()),
                ('Total_visitors', models.IntegerField()),
                ('Top1_Born_Place', models.CharField(max_length=255)),
                ('Top2_Born_Place', models.CharField(max_length=255)),
                ('Top3_Born_Place', models.CharField(max_length=255)),
                ('Top1_Number', models.FloatField()),
                ('Top2_Number', models.FloatField()),
                ('Top3_Number', models.FloatField()),
                ('Total_Number', models.IntegerField()),
                ('Buddhism', models.IntegerField()),
                ('Christianity', models.IntegerField()),
                ('Hinduism', models.IntegerField()),
                ('Islam', models.IntegerField()),
                ('Judaism', models.IntegerField()),
                ('Other_Religions', models.IntegerField()),
                ('Secular_Beliefs_and_Other_Spiritual_Beliefs_and_No_Religious_Affiliation', models.IntegerField()),
                ('Religious_affiliation_not_stated', models.IntegerField()),
                ('Year_12_or_equivalent', models.IntegerField()),
                ('Year_11_or_equivalent', models.IntegerField()),
                ('Year_10_or_equivalent', models.IntegerField()),
                ('Year_9_or_equivalent', models.IntegerField()),
                ('Year_8_or_below', models.IntegerField()),
                ('Did_not_go_to_school', models.IntegerField()),
                ('Highest_year_of_school_not_stated', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('None_of_the_selected_conditions', models.IntegerField()),
                ('Has_one_or_more_selected_long_term_health_conditions', models.IntegerField()),
                ('Own_child_children_only', models.IntegerField()),
                ('Own_child_children_and_other_children', models.IntegerField()),
                ('Other_children_only', models.IntegerField()),
                ('Total_employed', models.IntegerField()),
                ('Total_unemployed', models.IntegerField()),
                ('Not_in_the_labour_force', models.IntegerField()),
                ('Train', models.IntegerField()),
                ('Bus', models.IntegerField()),
                ('Ferry', models.IntegerField()),
                ('Tram_light_rail', models.IntegerField()),
                ('Taxi_ride_share_service', models.IntegerField()),
                ('Car_as_driver', models.IntegerField()),
                ('Car_as_passenger', models.IntegerField()),
                ('Truck', models.IntegerField()),
                ('Motorbike_scooter', models.IntegerField()),
                ('Bicycle', models.IntegerField()),
                ('Other', models.IntegerField()),
                ('Walked_only', models.IntegerField()),
            ],
        ),
    ]
