# Generated by Django 4.2.3 on 2023-07-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0009_suburbdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suburbdata',
            old_name='Has_one_or_more_selected_long_term_health_conditions',
            new_name='Long_term_health_conditions',
        ),
        migrations.RenameField(
            model_name='suburbdata',
            old_name='Secular_Beliefs_and_Other_Spiritual_Beliefs_and_No_Religious_Affiliation',
            new_name='Other_and_No_Religious_Affiliation',
        ),
    ]
